src/wordplease/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.routers import DefaultRouter

from blogs.views import lastest_posts, blogs_list, blog_detail, post_detail, NewPostView, NewBlogView
from users.views import LoginView, SignUpView, logout

from users.api import UserViewSet
from blogs.api import BlogViewSet, PostViewSet

router = DefaultRouter()
router.register("users", UserViewSet, base_name="users_api")
router.register("blogs", BlogViewSet, base_name="blogs_api")
router.register("posts", PostViewSet, base_name="posts_api")
router.register(r'blogs/(?P<blog_id>[0-9]+)/posts', PostViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', lastest_posts, name="index"),
    url(r'^blogs/?$', blogs_list, name="blog_list"),
    url(r'^blogs/(?P<slug>[\w.@+-]+)/?$', blog_detail, name="blog_detail"),
    url(r'^blogs/(?P<slug>[\w.@+-]+)/(?P<post_pk>[0-9]+)/?$', post_detail, name="post_detail"),
    url(r'^new_blog/?$', NewBlogView.as_view(), name="new_blog"),
    url(r'^new_post', NewPostView.as_view(), name="new_post"),
    url(r'^login',LoginView.as_view(), name="login"),
    url(r'^logout', logout, name="logout"),
    url(r'^signup',SignUpView.as_view(), name="signup"),

    #api
    url(r'^api/1.0/', include(router.urls)),
]

src/blogs/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Blog(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField('slug', max_length=100, unique=True, default="none")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=45)

    def __str__(self):
        return self.name



class Post(models.Model):
    title = models.CharField(max_length=30)
    summary = models.TextField()
    body = models.TextField()
    media = models.URLField()
    public = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.title

src/ui/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}Wordplease{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'ui/css/style.css' %}" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Wordplease</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'blog_list' %}">Blogs</a></li>
              {% if user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{user.username}} <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li><a href="{% url 'new_blog' %}">New blog</a></li>
                      {% if user.blog_set.all.first != None %}
                          <li><a href="{% url 'new_post' %}">New Post</a></li>
                      {% endif %}
                      <li role="separator" class="divider"></li>
                      {% for blog in user.blog_set.all %}
                        <li><a><strong>Mis blogs</strong></a></li>
                        <li><a href="{% url 'blog_detail' blog.slug %}">{{blog}}</a></li>
                      {% endfor %}
                      <li role="separator" class="divider"></li>
                      <li><a href="{% url 'logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% else %}
                <li><a href="{% url 'signup' %}">Sign-up</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>

              {% endif %}

          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


    <div class="container-fluid" id="wrap">
        {%block content %}{% endblock %}
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>